# Generated by Django 5.2.17 on 2026-09-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store_whatsapp",
                    models.CharField(
                        default="218910000000",
                        help_text="رقم واتساب المتجر الرسمي المعتمد للتواصل مع الزبائن",
                        max_length=32,
                    ),
                ),
                (
                    "manager_phones",
                    models.TextField(
                        default="218910000000",
                        help_text="أرقام هواتف المدراء لمتابعة الطلبات (مفصولة بفواصل)",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        default="مصرف الجمهورية",
                        help_text="اسم المصرف للحوالات المصرفية",
                        max_length=120,
                    ),
                ),
                (
                    "bank_account_holder",
                    models.CharField(
                        blank=True,
                        default="متجر H2O Floss ليبيا",
                        help_text="اسم صاحب الحساب أو المستفيد",
                        max_length=120,
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        blank=True,
                        default="001-123456-001",
                        help_text="رقم الحساب المصرفي",
                        max_length=64,
                    ),
                ),
                (
                    "bank_iban",
                    models.CharField(
                        blank=True,
                        default="LY00001001123456001",
                        help_text="رقم الآيبان (IBAN)",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات المتجر والواتساب",
                "verbose_name_plural": "إعدادات المتجر والواتساب",
            },
        ),
    ]
