# Generated by Django 5.2.17 on 2026-09-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppMessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_number", models.CharField(db_index=True, max_length=32)),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("CUSTOMER", "الزبون"),
                            ("STORE", "المتجر"),
                            ("MANAGER", "المدير"),
                        ],
                        max_length=16,
                    ),
                ),
                ("recipient_phone", models.CharField(max_length=32)),
                ("message_text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "تم الإرسال تلقائياً"),
                            ("FAILED", "فشل الإرسال"),
                        ],
                        default="SENT",
                        max_length=16,
                    ),
                ),
                ("response_payload", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "سجل رسائل الواتساب التلقائية",
                "verbose_name_plural": "سجلات رسائل الواتساب التلقائية",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="storesettings",
            name="whatsapp_auto_send",
            field=models.BooleanField(
                default=True,
                help_text="إرسال الفاتورة والإشعارات تلقائياً للزبون والإدارة فور تسجيل الطلب",
            ),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="whatsapp_gateway_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="مفتاح API Token للبوابة (اختياري)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="whatsapp_gateway_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="رابط Webhook أو بوابة الواتساب API الخارجية (اختياري)",
                max_length=255,
            ),
        ),
    ]
