# Generated by Django 5.2.17 on 2026-09-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_whatsappmessagelog_storesettings_whatsapp_auto_send_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramMessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_number", models.CharField(db_index=True, max_length=32)),
                ("chat_id", models.CharField(max_length=64)),
                ("message_text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("SENT", "تم الإرسال"), ("FAILED", "فشل الإرسال")],
                        default="SENT",
                        max_length=16,
                    ),
                ),
                ("response_payload", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "سجل رسائل تيليجرام",
                "verbose_name_plural": "سجلات رسائل تيليجرام",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AlterModelOptions(
            name="storesettings",
            options={
                "verbose_name": "إعدادات المتجر والإشعارات",
                "verbose_name_plural": "إعدادات المتجر والإشعارات",
            },
        ),
        migrations.AddField(
            model_name="storesettings",
            name="telegram_bot_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="توكن بوت تيليجرام (يُنشأ من BotFather)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="telegram_chat_ids",
            field=models.TextField(
                blank=True,
                default="",
                help_text="معرّفات المحادثة (Chat ID) للمدراء، مفصولة بفواصل",
            ),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="telegram_enabled",
            field=models.BooleanField(
                default=False,
                help_text="إرسال إشعار بكل طلب جديد إلى المدير عبر تيليجرام",
            ),
        ),
    ]
