# Generated by Django 5.2.17 on 2026-08-29 09:40

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="البريد الإلكتروني"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="الاسم")),
                ("phone", models.CharField(max_length=20, verbose_name="الهاتف")),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("tripoli", "طرابلس"),
                            ("benghazi", "بنغازي"),
                            ("misrata", "مصراتة"),
                            ("zawiya", "الزاوية"),
                            ("zliten", "زليتن"),
                            ("ajdabiya", "أجدابيا"),
                            ("bayda", "البيضاء"),
                            ("tobruk", "طبرق"),
                            ("khoms", "الخمس"),
                            ("sirt", "سرت"),
                            ("derna", "درنة"),
                            ("sabha", "سبها"),
                            ("sabratha", "صبراتة"),
                            ("zuwara", "زوارة"),
                            ("tarhuna", "ترهونة"),
                            ("gharyan", "غريان"),
                            ("bani_walid", "بني وليد"),
                            ("marj", "المرج"),
                            ("kufra", "الكفرة"),
                            ("nalut", "نالوت"),
                            ("yafran", "يفرن"),
                            ("msallata", "مسلاتة"),
                        ],
                        default="tripoli",
                        max_length=20,
                        verbose_name="المدينة",
                    ),
                ),
            ],
            options={
                "verbose_name": "عميل",
                "verbose_name_plural": "العملاء",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, verbose_name="الاسم")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="الهاتف"),
                ),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "is_handled",
                    models.BooleanField(default=False, verbose_name="تمت المعالجة"),
                ),
            ],
            options={
                "verbose_name": "رسالة تواصل",
                "verbose_name_plural": "رسائل التواصل",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalOrder",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=24,
                        verbose_name="رقم الطلب",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=120, verbose_name="الاسم الكامل"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="الهاتف")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="البريد الإلكتروني"),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("tripoli", "طرابلس"),
                            ("benghazi", "بنغازي"),
                            ("misrata", "مصراتة"),
                            ("zawiya", "الزاوية"),
                            ("zliten", "زليتن"),
                            ("ajdabiya", "أجدابيا"),
                            ("bayda", "البيضاء"),
                            ("tobruk", "طبرق"),
                            ("khoms", "الخمس"),
                            ("sirt", "سرت"),
                            ("derna", "درنة"),
                            ("sabha", "سبها"),
                            ("sabratha", "صبراتة"),
                            ("zuwara", "زوارة"),
                            ("tarhuna", "ترهونة"),
                            ("gharyan", "غريان"),
                            ("bani_walid", "بني وليد"),
                            ("marj", "المرج"),
                            ("kufra", "الكفرة"),
                            ("nalut", "نالوت"),
                            ("yafran", "يفرن"),
                            ("msallata", "مسلاتة"),
                        ],
                        default="tripoli",
                        max_length=20,
                        verbose_name="المدينة",
                    ),
                ),
                ("address", models.TextField(verbose_name="العنوان")),
                ("note", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "قيد المراجعة"),
                            ("APPROVED", "تمت الموافقة"),
                            ("COMPLETED", "مكتمل"),
                            ("REJECTED", "مرفوض"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="المجموع الفرعي",
                    ),
                ),
                (
                    "shipping",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="الشحن",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="الإجمالي",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="orders.client",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical طلب",
                "verbose_name_plural": "historical الطلبات",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=24,
                        unique=True,
                        verbose_name="رقم الطلب",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=120, verbose_name="الاسم الكامل"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="الهاتف")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="البريد الإلكتروني"),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("tripoli", "طرابلس"),
                            ("benghazi", "بنغازي"),
                            ("misrata", "مصراتة"),
                            ("zawiya", "الزاوية"),
                            ("zliten", "زليتن"),
                            ("ajdabiya", "أجدابيا"),
                            ("bayda", "البيضاء"),
                            ("tobruk", "طبرق"),
                            ("khoms", "الخمس"),
                            ("sirt", "سرت"),
                            ("derna", "درنة"),
                            ("sabha", "سبها"),
                            ("sabratha", "صبراتة"),
                            ("zuwara", "زوارة"),
                            ("tarhuna", "ترهونة"),
                            ("gharyan", "غريان"),
                            ("bani_walid", "بني وليد"),
                            ("marj", "المرج"),
                            ("kufra", "الكفرة"),
                            ("nalut", "نالوت"),
                            ("yafran", "يفرن"),
                            ("msallata", "مسلاتة"),
                        ],
                        default="tripoli",
                        max_length=20,
                        verbose_name="المدينة",
                    ),
                ),
                ("address", models.TextField(verbose_name="العنوان")),
                ("note", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "قيد المراجعة"),
                            ("APPROVED", "تمت الموافقة"),
                            ("COMPLETED", "مكتمل"),
                            ("REJECTED", "مرفوض"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="المجموع الفرعي",
                    ),
                ),
                (
                    "shipping",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="الشحن",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="الإجمالي",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="orders.client",
                        verbose_name="العميل",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب",
                "verbose_name_plural": "الطلبات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField()),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "عنصر طلب",
                "verbose_name_plural": "عناصر الطلبات",
                "ordering": ["id"],
            },
        ),
    ]
