# Generated by Django 5.2.17 on 2026-09-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH_ON_DELIVERY", "دفع عند الاستلام (كاش)"),
                    ("BANK_TRANSFER", "تحويل مصرفي عبر واتساب"),
                ],
                default="CASH_ON_DELIVERY",
                max_length=30,
                verbose_name="طريقة الدفع",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH_ON_DELIVERY", "دفع عند الاستلام (كاش)"),
                    ("BANK_TRANSFER", "تحويل مصرفي عبر واتساب"),
                ],
                default="CASH_ON_DELIVERY",
                max_length=30,
                verbose_name="طريقة الدفع",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="البريد الإلكتروني"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(
                db_index=True, max_length=20, unique=True, verbose_name="الهاتف"
            ),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="البريد الإلكتروني"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="البريد الإلكتروني"
            ),
        ),
    ]
