# Generated by Django 5.2.17 on 2026-09-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_historicalorder_payment_method_order_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="is_seen",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="طلب جديد لم تتم مشاهدته بعد من لوحة التحكم",
                verbose_name="تمت المشاهدة",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_seen",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="طلب جديد لم تتم مشاهدته بعد من لوحة التحكم",
                verbose_name="تمت المشاهدة",
            ),
        ),
    ]
