# Generated by Django 5.2.17 on 2026-09-19 08:24

from django.db import migrations, models


def merge_duplicate_order_items(apps, schema_editor):
    OrderItem = apps.get_model("orders", "OrderItem")
    duplicates = (
        OrderItem.objects.values("order_id", "product_id")
        .annotate(
            row_count=models.Count("id"),
            total_quantity=models.Sum("quantity"),
            total_value=models.Sum("line_total"),
        )
        .filter(row_count__gt=1)
    )
    for duplicate in duplicates:
        duplicate_lines = OrderItem.objects.filter(
            order_id=duplicate["order_id"],
            product_id=duplicate["product_id"],
        ).order_by("id")
        retained_line = duplicate_lines.first()
        retained_line.quantity = duplicate["total_quantity"]
        retained_line.line_total = duplicate["total_value"]
        retained_line.save(update_fields=["quantity", "line_total"])
        duplicate_lines.exclude(pk=retained_line.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("orders", "0003_historicalorder_is_seen_order_is_seen"),
    ]

    operations = [
        migrations.RunPython(
            merge_duplicate_order_items,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "product"), name="orders_one_line_per_product"
            ),
        ),
    ]
