# Generated by Django 5.2.17 on 2026-08-29 05:37

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "is_parts_group",
                    models.BooleanField(
                        default=False, help_text="تُعرض ضمن قسم «أجزاء وملحقات الجهاز»."
                    ),
                ),
            ],
            options={
                "verbose_name": "قسم",
                "verbose_name_plural": "الأقسام",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalProduct",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("DEVICE", "الجهاز الرئيسي"),
                            ("PART", "قطعة غيار"),
                            ("ACCESSORY", "ملحق"),
                            ("KIT", "طقم"),
                        ],
                        db_index=True,
                        default="PART",
                        max_length=10,
                    ),
                ),
                (
                    "hero",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="منتج الصفحة الرئيسي — واحد فقط في المتجر.",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="HTML مُنقّى تلقائياً عند الحفظ."
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='مثال: {"الخزان": "300 مل", "الأوضاع": "5"}',
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="LYD", max_length=3)),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="اتركه فارغاً = «متوفر عند الطلب» بلا سقف.",
                        null=True,
                    ),
                ),
                ("weight_grams", models.PositiveIntegerField(blank=True, null=True)),
                ("warranty_months", models.PositiveIntegerField(default=24)),
                ("main_image", models.TextField(blank=True, max_length=100, null=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="يظهر في الصفحة الرئيسية."
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "بدون شارة"),
                            ("NEW", "جديد"),
                            ("HOT", "الأكثر مبيعاً"),
                            ("SALE", "تخفيض"),
                        ],
                        default="",
                        max_length=4,
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalog.category",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical منتج",
                "verbose_name_plural": "historical المنتجات",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("DEVICE", "الجهاز الرئيسي"),
                            ("PART", "قطعة غيار"),
                            ("ACCESSORY", "ملحق"),
                            ("KIT", "طقم"),
                        ],
                        db_index=True,
                        default="PART",
                        max_length=10,
                    ),
                ),
                (
                    "hero",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="منتج الصفحة الرئيسي — واحد فقط في المتجر.",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="HTML مُنقّى تلقائياً عند الحفظ."
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='مثال: {"الخزان": "300 مل", "الأوضاع": "5"}',
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="LYD", max_length=3)),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="اتركه فارغاً = «متوفر عند الطلب» بلا سقف.",
                        null=True,
                    ),
                ),
                ("weight_grams", models.PositiveIntegerField(blank=True, null=True)),
                ("warranty_months", models.PositiveIntegerField(default=24)),
                (
                    "main_image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="يظهر في الصفحة الرئيسية."
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "بدون شارة"),
                            ("NEW", "جديد"),
                            ("HOT", "الأكثر مبيعاً"),
                            ("SALE", "تخفيض"),
                        ],
                        default="",
                        max_length=4,
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
                (
                    "devices",
                    models.ManyToManyField(
                        blank=True,
                        help_text="الأجهزة التي تعمل مع هذه القطعة.",
                        limit_choices_to={"kind": "DEVICE"},
                        related_name="compatible_parts",
                        to="catalog.product",
                    ),
                ),
                (
                    "kit_contents",
                    models.ManyToManyField(
                        blank=True,
                        help_text="للأطقم فقط: القطع المضمونة في الطقم.",
                        related_name="included_in",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "منتج",
                "verbose_name_plural": "المنتجات",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="products/")),
                ("caption", models.CharField(blank=True, max_length=150)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "is_feature",
                    models.BooleanField(
                        default=False, help_text="تظهر في بطاقة المنتج."
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة منتج",
                "verbose_name_plural": "صور المنتجات",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("old_price__isnull", False),
                    ("old_price__lte", models.F("price")),
                    _negated=True,
                ),
                name="catalog_old_price_above_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("hero", True)),
                fields=("hero",),
                name="catalog_hero_product_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("hero", False), ("kind", "DEVICE"), _connector="OR"
                ),
                name="catalog_hero_is_device",
            ),
        ),
    ]
